import Head from 'next/head'
import Image from 'next/image'
import { Layout, Menu, Breadcrumb } from 'antd';
import styles from '../styles/Home.module.css'
import 'antd/dist/antd.css';

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyAsFOOfSNZkW3VC2jQ6F5oP5mlXJx2AIWM",
  authDomain: "astro-752f0.firebaseapp.com",
  databaseURL: "https://astro-752f0-default-rtdb.firebaseio.com",
  projectId: "astro-752f0",
  storageBucket: "astro-752f0.appspot.com",
  messagingSenderId: "564655985099",
  appId: "1:564655985099:web:54575ec06cfd523cec264e"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

const nav = [
  {
    key: 'home',
    text: 'Home',
    href: '/',
    icon: 'home',
  },
  {
    key: 'manage',
    text: 'Manage',
    href: '/manage',
    icon: 'manage',
  },
]

const { Header, Content, Footer } = Layout;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Astro Management Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className="layout">
        <Header>
          <div className="logo" />
          <Menu theme="dark" mode="horizontal" defaultSelectedKeys={['2']}>
            {nav.map(item => (
              <Menu.Item key={item.key}>
                <a href={item.href}>
                  <span>{item.text}</span>
                </a>
              </Menu.Item>
            ))}
          </Menu>
        </Header>
        <Content style={{ padding: '0 50px' }}>
          <div className="site-layout-content">Content</div>
        </Content>
        <Footer style={{ textAlign: 'center' }}>Astro loads</Footer>
      </Layout>

    </div>
  )
}
